### ISSUE TITLE
Unknown projection '3d'

### ISSUE THREAD

**Issue by ahmaddidiks** [dbddqy/visual_kinematics#2]
I just wanna test example of invers, but I got this
![error](https://user-images.githubusercontent.com/23350636/124697032-55fc4900-df10-11eb-84fa-2906341e2fe4.png)

**Comment by nodyyu89** [comment]
try add this in your script:

`import matplotlib.pyplot as plt`
`from mpl_toolkits.mplot3d import Axes3D`

[https://stackoverflow.com/questions/56222259/valueerror-unknown-projection-3d-once-again](url)

**Comment by ahmaddidiks** [comment]
Thanks mate. Your repo helped my BE thesis, and I graduated last year.
